services:
  frontend:
    image: node:22-alpine
    container_name: plg-frontend
    working_dir: /app
    volumes:
      - ./frontend-client:/app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://127.0.0.1:9600"
      HOST: "0.0.0.0"
      PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm start"
    restart: unless-stopped